# ==== JVM ====
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# ==== Android ====
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true

# ==== Kotlin ====
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.cacheKind=static
kotlin.native.binary.memoryModel=experimental
kotlin.incremental=true
kotlin.version=1.9.22

# ==== Build performance ====
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.warning.mode=all

# ==== Compose (si besoin) ====
android.compose.multiplatform.enabled=true
